### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by GusTheBusNG**
Adding the new homepage and making the ability to add and remove ensembles like the past cu-singers

*This may break the admin panel for the landing page*

### CODE REVIEW

**Comment by GusTheBusNG** [comment]
We should only merge this if we need it for further development of other tasks. The landing page admin panel is broken. I'll look into a fix.

**Comment by apatyk** [comment]
Agreed, I think it will be useful to leave it un-merged for the time being.

**Comment by apatyk** [comment]
Other than that, it looks good to me.

**Review by apatyk — COMMENTED** [review]
👌

**Review by apatyk — APPROVED** [review]

**Pull request merged**
